<?php
namespace Light\ObjectService\Resource;

use Light\ObjectService\Mockup\Database;
use Light\ObjectService\Mockup\EndpointSetup;
use Light\ObjectService\Mockup\Post;
use Light\ObjectService\Mockup\PostModel;
use Light\ObjectService\Resource\Addressing\ResourceIdentifier;
use Light\ObjectService\Resource\Operation\ResourceUpdateSpecification;

class ResourceSpecificationTest extends \PHPUnit_Framework_TestCase
{
	/** @var EndpointSetup */
	private $endpointSetup;

	protected function setUp()
	{
		parent::setUp();

		$this->endpointSetup = new EndpointSetup();
	}

	public function testExistingResourceSpecification()
	{
		$spec = new ExistingResourceSpecification(ResourceIdentifier::createFromUrl("http://example.org/endpoint/blog/posts/141"));
		$resolved = $spec->resolve($this->endpointSetup->getExecutionParameters());

		$this->assertNotNull($resolved);
		$this->assertSame($resolved->getValue(), Database::$posts[0]);
	}

	public function testNewResourceSpecification()
	{
		$type = $this->endpointSetup->getEndpoint()->getObjectRegistry()->getType(Post::CLASSNAME);
		$updateSpec = new ResourceUpdateSpecification();
		$updateSpec->setValue("title", "My new post");

		$spec = new NewResourceSpecification($type, $updateSpec);
		$resolvedValue = $spec->resolve($this->endpointSetup->getExecutionParameters());

		$this->assertEquals(PostModel::$autoId, $resolvedValue->getValue()->id);
		$this->assertEquals("My new post", $resolvedValue->getValue()->title);
		$this->assertSame($type, $resolvedValue->getType());

		// TODO: Test autogenerated URL for this new object.
	}

}
 